#+TITLE: User Guide to Mathcad Automation Software
#+author: Piero Panariello
#+subtitle: Applies to Mathcad Automation v1.0 and above
#+OPTIONS: toc:t
#+OPTIONS: ^:nil
#+STARTUP: showeverything
#+LATEX_CLASS-OPTIONS: [letterpaper]
#+LATEX_HEADER: \usepackage[letterpaper, portrait, margin=1in]{geometry}
#+LATEX_HEADER: \author{Piero Panariello}
#+LATEX_HEADER: \documentclass[7pt]


* About
This program is designed to help automate the heavy lifting of data entry into Mathcad for the equipment anchorage process. It helps you view and modify values taken from an excel spreadsheet before generating a mathcad report.

Please note that this is only compatible with Mathcad Prime 5.0 and above.
[[https://youtu.be/aOWT9xCHb2I][Tutorial Video]]

* Installation
1. Go to the releases tab on this github page, find the latest distribution and download it. Download the template files provided to help you get started.
2. Double click the application executable to launch the application.
* Use
Select the excel file from the templates provided containing the equipment and the input data. The excel sheet should have the following key headers:
|----------------------------+-------------------+----------------+-------------+---------+-----------|
| eqpt_name                  | mounting_location | project_number | eqpt_number | tags    | eqpt_tags |
|----------------------------+-------------------+----------------+-------------+---------+-----------|
| Anesthesia machine         | Wall, Floor       |           1111 |        1234 | Medical | Foo, Bar  |
| Warming Cabinet            | Floor             |           1111 |        1234 | Medical | Foo       |
| Surgical Scrub Sink        | Wall              |           1111 |        1234 | Medical | Bar       |
| Retractable Ceiling Column | Ceiling           |           1111 |        1234 | Medical | Foo, Bar  |
|----------------------------+-------------------+----------------+-------------+---------+-----------|
Note: Tags should be separated by comma. If you decide to include units, put parentheses around the unit and do not include any spaces in the header. There must be two sheets - *values* or *Calculations* and *preview_images*. Take a look at the provided excel template for reference.
1. Select your Mathcad template file for each mounting location. I have provided a single file that works for each location to help you get started. It is located on the same page as the latest distribution. If the template you chose does not work, make sure that it is compatible with your current Mathcad distribution.  
2. You can always go back to the file selection screen by clicking *File->Change Input Files* from the main screen. You can reload the information from the excel spreadsheet by clicking *Edit->Revert Inputs*.
3. If you want to save details about the report to the database, then click *Save to Database* in the Change Input Files window. See the section ~Database~ for more information.
4. Click the *Previous* or *Next* buttons to scroll the equipment listed in your excel file.
5. Click the *Preview Calculation Outputs* button to preview the output values.
6. Click the *Generate Report* button and provide a file name to generate a report for the equipment. You do not need to provide a filename if you are generating a report for all equipment entries.
7. The application is processing your request once you click *Generate Report* or *Generate Report For All*. A confirmation popup will appear when the processing is complete. Be patient - the Mathcad API is not very fast and unfortunately there is no way to speed it up. You can do whatever tasks you like in the background. 
* Database
1. The "database" is a .csv file containing all the calculations you have performed with the automation software. This helps with organization and future reference.
2. Choose the database that you want your generated reports to be appended to. If you choose an already existing database, your new reports will automatically be appended. You can leave this field blank: a database file will automatically be generated in the *mathcad_automation_output* folder, and the new reports will be appended.
3. You can view the database file by 
* Important Information
1. Make sure to select the appropriate Mathcad template file from the teplates provided. If you are using Mathcad Prime 5.0, you must use a file compatible with that version. Mathcad Prime is backward compatible, however, older files can be run on more modern versions of the software.
2. If you would like to change the output folder (where all reports and the database file are saved) then specify it in *File->Select Output Folder*. 
3. All Generated reports are saved to a folder called *mathcad_automation_output*. This folder is created (if it doesn't exist already) in the same directory as the application. If you specify an output folder, it will be used instead. 
4. Customizing the App:
   - If you decide to you want to include your own inputs and outputs, make sure to label your inputs *<my_label>_input*. For example, *alpha_input* would work, but *alpha_something* would not.
   - To use your own custom Mathcad template, choose it using the *Change Input Files* button. Ensure the format follows the example Mathcad template provided.
   - To use your own custom excel file, choose it using *File->Change Input Files* or the shortcut *Ctrl-i*. Your custom file must follow the formatting rules explicitly defined in the example excel document.
   - To save the inputs from the application back to the excel file, click *File->Save Inputs To Excel* or the shortcut *Ctrl-s*. 
